### ISSUE TITLE
Bars are not rendered side-by-side in Grafana 5.1.3

### ISSUE THREAD

**Issue by jorelcantero** [CorpGlory/grafana-multibar-graph-panel#12]
I think it may be error similar #3 

![image](https://user-images.githubusercontent.com/9268371/41733653-e361b7b2-755a-11e8-90d2-73ce861a88b7.png)

**Comment by jonyrock** [comment]
@matthenning can you please help us with that? :)

**Comment by kccheung** [comment]
+1, can someone please make it support the latest version of grafana (5.2.3)?

**Comment by jonyrock** [comment]
@kccheung we have no time, sorry

**Comment by srinathganesh** [comment]
in grafana 5.2.4, when I start grafana with a volume, the plugin get installed and show but there side by side checkbox does not work

while without volume it does work (sometimes!) suddenly in the saved graph the view stops showing it side by side, and when i restart docker a few times then it starts to show it.

**Comment by jonyrock** [comment]
@rozetko @sankerust please check the status of bug

**Comment by rozetko** [comment]
Tried to reproduce it using Grafana 5.2.4 with `/var/lib/grafana/plugins` as volume, it works now
Guess it was fixed in one of recent releases
@srinathganesh @kccheung @jorelcantero would you try the latest release?
https://github.com/CorpGlory/grafana-multibar-graph-panel/releases/download/0.2.3/grafana-multibar-graph-panel-0.2.3.tar.gz

**Comment by jorelcantero** [comment]
@rozetko Fisrt I'm sorry for taking so long to respond.
The release 0.2.3 fixes reported error. Thanks
